#!/bin/bash
# A simple wrapper for changing a user's password.
# This provides a clean name for the pkexec authentication prompt.
# Argument 1 ($1) is the username.
# The new password is read from standard input.

/usr/bin/passwd --stdin "$1"
